blank_issues_enabled: true
contact_links:
  - name: â„¹ Questions, Ideas, and Discussions
    url: https://github.com/MithrilJS/mithril.js/discussions
    about: |
      Got a question on how to use Mithril.js? Have a fancy idea of how we could do better? Check
      out our discussions forum!
  - name: â„¹ Show and Tell
    url: https://github.com/MithrilJS/mithril.js/discussions/new?category=show-and-tell
    about: |
      Got something to show off? Made something so cool, you just have to tell the world? Let us
      know here in our discussions forum!
  - name: ðŸš€ Feature Request or Enhancement
    url: https://github.com/MithrilJS/mithril.js/discussions/new?category=ideas
    about: Got a feature request? Let us know here! We do those in our discussion forum.
  - name: ðŸ“„ Documentation issue
    url: https://github.com/MithrilJS/docs
    about: Found an issue with our documentation? File that in our docs repo instead.
  - name: ðŸ’» Zulip Chat
    url: https://mithril.zulipchat.com/
    about: Not sure about something? Just want to hang out? Come over to our Zulip chat!
